# Generated by Django 5.2.13 on 2026-05-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasis_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='url_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
